# Generated by Django 5.0.1 on 2024-01-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_post_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="post",
            name="artist",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
