# Generated by Django 5.0.1 on 2024-01-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_tag_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="tag",
            name="order",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
